version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      cluster.name: "docker-cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "0"